export const sample_projects = [
  {
    id: "1",
    name: "Пещера „Бисерна“",
    price: 45,
    area: 300,
    category: "residential",
    images: [
      "http://localhost:5173/public/images/cave-biserna/1.jpg",
      "http://localhost:5173/public/images/cave-biserna/2.jpg",
      "http://localhost:5173/public/images/cave-biserna/3.jpg",
      "http://localhost:5173/public/images/cave-biserna/4.jpg",
      "http://localhost:5173/public/images/cave-biserna/5.jpg",
      "http://localhost:5173/public/images/cave-biserna/6.jpg",
      "http://localhost:5173/public/images/cave-biserna/7.jpg",
    ],
    description: "Пещера „Бисерна“ is a cave attraction.",
    comments: [],
  },
  {
    id: "2",
    name: "Панорамна алея „Стъпалата“",
    price: 35,
    area: 400,
    category: "industrial",
    images: [
      "http://localhost:5173/public/images/stapalata/1.jpg",
      "http://localhost:5173/public/images/stapalata/2.jpg",
      "http://localhost:5173/public/images/stapalata/3.jpg",
      "http://localhost:5173/public/images/stapalata/4.jpg",
      "http://localhost:5173/public/images/stapalata/5.jpg",
      "http://localhost:5173/public/images/stapalata/6.jpg",
      "http://localhost:5173/public/images/stapalata/7.jpg",
    ],
    description: "Панорамна алея „Стъпалата“ offers a scenic walkway.",
    comments: [],
  },
  {
    id: "3",
    name: "Природен парк „Българка“",
    price: 40,
    area: 500,
    category: "urban",
    images: [
      "http://localhost:5173/public/images/bulgarka/1.jpg",
      "http://localhost:5173/public/images/bulgarka/2.jpg",
      "http://localhost:5173/public/images/bulgarka/3.jpg",
      "http://localhost:5173/public/images/bulgarka/4.jpg",
      "http://localhost:5173/public/images/bulgarka/5.jpg",
      "http://localhost:5173/public/images/bulgarka/6.jpg",
      "http://localhost:5173/public/images/bulgarka/7.jpg",
    ],
    description: "Природен парк „Българка“ is a natural park.",
    comments: [],
  },
  {
    id: "4",
    name: "Астрономическа обсерватория в ПП „Шуменско плато“",
    price: 30,
    area: 370,
    category: "public",
    images: [
      "http://localhost:5173/public/images/observatory/1.jpg",
      "http://localhost:5173/public/images/observatory/2.jpg",
      "http://localhost:5173/public/images/observatory/3.jpg",
      "http://localhost:5173/public/images/observatory/4.jpg",
      "http://localhost:5173/public/images/observatory/5.jpg",
    ],
    description:
      "Астрономическа обсерватория at Шуменско плато is an astronomical observatory.",
    comments: [],
  },

  {
    id: "5",
    name: "Historic Library",
    price: 60,
    area: 250,
    category: "public",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1kxB5FrWy6C_Ud8wK7b33Wq34ab-JHMZkoQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfzMRLlKpAiphgdqzbMAEJ3ueluLg9OVh48YpXxrdV_EzNrpoKQ5gHxD59ams7D2ayVQA&usqp=CAU",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJyliDoqfwTnAx37W5n29-Yv_Nr7ya2Y2bk6NfguIMpDlykihBMAUbjpIWSxxzqzvfaHE&usqp=CAU",
    ],
    description: "A beautifully preserved historic library.",
    comments: [],
  },
  {
    id: "6",
    name: "Modern Art Museum",
    price: 75,
    area: 350,
    category: "public",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDwDm2ZDpdV4h1jCsnkYyXIDlVimCmWWWhYQ&s",
      "https://media.cntraveler.com/photos/5dae0325b45cd80008161cf3/master/pass/MOMA-2019_IVRPHOTO-4373_ArtistChoice_HB_007-2-2000x1125.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAaujj0bxwluj_KEaNl62cndu65tiur2kzdPNZNhkDQQsF9EO3yvzHz9OkoapaDihzQQs&usqp=CAU",
    ],
    description: "A contemporary museum showcasing modern art.",
    comments: [],
  },
  {
    id: "7",
    name: "High-Tech Office Building",
    price: 90,
    area: 500,
    category: "industrial",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkM3r_uCYccRFehkixjt2PW8BGrL0Q8XFopQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPVVxhf8jyqIXdv_MCxhACzFtj9cLNyXIa1g&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjHewjqu9v3xDnLSIAHc6oLCCXts5yoaMKxTFO0fU_3R3mFsa07El5zchyg0RmqO-5KO0&usqp=CAU",
    ],
    description: "A state-of-the-art office building for tech companies.",
    comments: [],
  },
  {
    id: "8",
    name: "Luxury Apartment Complex",
    price: 120,
    area: 600,
    category: "residential",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0oFOEDyoPjxY-nrwQCYRuKfFgt10qhAwURQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxjCn_NFnUgLQ0WMSmDhpP6lV28Z7qu3vKQJQD_W_0x0LjBY8gxW5x4pAYEIrczCHfpQs&usqp=CAU",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXP7BdfazloS-XmxZZa1jGPsWxmrdHaLCW3c3of1o-UchKl9zFRdNpY3usF9kQtYiV84s&usqp=CAU",
    ],
    description: "A high-end residential complex with luxury apartments.",
    comments: [],
  },
  {
    id: "9",
    name: "Urban Park Redevelopment",
    price: 85,
    area: 450,
    category: "urban",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnGVuhYAx7vPxumM1G2QEa3XcOBugRVDJgnA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnovoIE3LWRsJymQjx9TF62kMEbSevyzrPxC-dawQMBhZzp2K5zabXaZID-zkydQ5-_pc&usqp=CAU",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD54DJdCrVzW24-Fp4uml_n5TzU-9G0zcz1I5Oh72qWgnVVanzyaHH9vuTt1vneSpSniI&usqp=CAU",
    ],
    description: "Revitalization of a city park with modern features.",
    comments: [],
  },
  {
    id: "10",
    name: "Sustainable Greenhouse",
    price: 55,
    area: 200,
    category: "industrial",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDJ8EsoDtobf1Ei81LzFwdX7pFFhlvLlpHhg&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJy2pE1GOES02nKg-RZndD3Lk67e3JJnxRSjTsdWgaX6Em26msVQYoZ3BKqYLA_noKWgI&usqp=CAU",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRqyvnop2ua3qyWgPHkE9GEBj_OsUlqobjazE-ORkyLfzVhBYRQSMsEGEJMAq0U87CRRU&usqp=CAU",
    ],
    description: "An eco-friendly greenhouse designed for sustainability.",
    comments: [],
  },
  {
    id: "11",
    name: "Contemporary Art Gallery",
    price: 70,
    area: 300,
    category: "public",
    images: [
      "https://images.adsttc.com/media/images/5013/0b9b/28ba/0d06/5800/0d76/large_jpg/stringio.jpg?1414581067",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZyY3pW_YtlHN6uRiBCoypFLz3OpfqA3HSqwHZi3VEsCy8Qk2xlIMWvZQVSCbtkn4SV7Q&usqp=CAU",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2xSCTm1FObgk3FeN_p_NPYDBe0NbRbbIFwOLxT0csP8WWaHOWnN9aXuUHJaKnVPFgQB8&usqp=CAU",
    ],
    description: "A gallery showcasing contemporary artworks.",
    comments: [],
  },
  {
    id: "12",
    name: "Smart City Hub",
    price: 95,
    area: 700,
    category: "urban",
    images: [
      "https://b-amsterdam.com/wp-content/uploads/2023/07/B-amsterdam-bedrijfshal-1.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc_XVNE7ERfGYDO_WcJVqCi1WyXY9Wy0qZ52CVGVcTMjofT4nDEDMu7wtAGrM-GBZ2ce4&usqp=CAU",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWEtb6ZwO3wvUd-QgaQ6ktIUdSb0RplkYif-ehQfgwiZo3Heou8SOLJ_ewMUydwVhXfy8&usqp=CAU",
    ],
    description: "A central hub for smart city initiatives and technology.",
    comments: [],
  },
  {
    id: "13",
    name: "Eco-Friendly Office Space",
    price: 85,
    area: 400,
    category: "industrial",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxtsdUiqF87-a0rjrMZ1DBVNlcb9-3Dn8rqg&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNqBadZRjqFkVhIfANJ6Kx6ARnVFcJt30f5r3LrYZsMkvRrQ4KSfw_AHt1bSzD5KNyWkM&usqp=CAU",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiqW9XLF7F35vCWnn8tSTbl0eo9Fx48YqgvkuTOvtwgbIDsgoXBAKhOwdWY1laWD9N2Xw&usqp=CAU",
    ],
    description: "An office space designed with sustainability in mind.",
    comments: [],
  },
  {
    id: "14",
    name: "Innovative Urban Loft",
    price: 80,
    area: 400,
    category: "residential",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTb6oao70TF2WnOwfAyhCTdM8sY6bfX3X-OA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD1HWbTWlRjxiOxQgWQjXlC_dTZguk-9I4mOlZMX3PFOZZEwOco7OMBaAk7mkTUZ7LPLw&usqp=CAU",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWkCXk0Xmmg3g2paPSuDKi5iRcr24xhX52xTS0jaX2cgoI10kFyY9l4jsyozpAOnZkQgE&usqp=CAU",
    ],
    description: "A creative and stylish loft in the heart of the city.",
    comments: [],
  },
  {
    id: "15",
    name: "Urban Skyscraper",
    price: 100,
    area: 800,
    category: "industrial",
    images: [
      "https://assets.newatlas.com/dims4/default/180b7c9/2147483647/strip/true/crop/3840x2154+0+0/resize/2880x1616!/quality/90/?url=http%3A%2F%2Fnewatlas-brightspot.s3.amazonaws.com%2F25%2Fbb%2Fef0ed9794c3ea3ec8c5c79774439%2Frnd300-033-n11-jpg.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8yF_K8p4ihaNP8EzeI0DH-AtxCTvZCNGsoZBTUAtvytqDG-g7Ooapwp-jcZxK2b62Sh8&usqp=CAU",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC8L27edG_K6FeX1kFp8TC1Fcbry-Z2PB3FoyNxacEi3rB0qaS7tnXU2fbN4bu17QLklw&usqp=CAU",
    ],
    description: "A towering skyscraper with a modern design.",
    comments: [],
  },
  {
    id: "16",
    name: "Luxury Yacht Design",
    price: 120,
    area: 100,
    category: "industrial",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQefKi6cG-q0fdHtr_L-U5LtA4kibahfJ8Z2g&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNQIq2ZlzfmNBjwK4MlW8jieN9K-N2H3QgDw&s",
      "https://www.home-designing.com/wp-content/uploads/2014/05/6-Luxury-platform-bed.jpg",
    ],
    description: "A high-end yacht designed for luxury and comfort.",
    comments: [],
  },
];
